### ISSUE TITLE
Autobot1M数据集问题

### ISSUE THREAD

**Issue by lalaulalal** [Event-AHU/VehicleMAE#2]
请问Autobot1M数据集中，文本标注对应的图片列表能提供吗？另外，请问supplementary文档能发一份吗（或路径）？谢谢！

**Comment by Vehicle-AHU** [comment]
> 请问Autobot1M数据集中，文本标注对应的图片列表能提供吗？另外，请问supplementary文档能发一份吗（或路径）？谢谢！

不好意思，我们没有整理文本标注对应的图片列表，因此无法提供。对于supplementary文档，你可以查看我们提交的arxiv版本论文。https://arxiv.org/abs/2312.09812
